# Official image for Hashicorp's Terraform. It uses light image which is Alpine
# based as it is much lighter.
#
# Entrypoint is also needed as image by default set `terraform` binary as an
# entrypoint.

image:
   name: hashicorp/terraform:light
   entrypoint:
     - '/usr/bin/env'
     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
     -  rm -rf .terraform
     -  terraform --version
     -  mkdir -p ./creds
     -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
     -  terraform init

stages:
      - validate
      - plan
      - apply
      - destroy

validate:
   stage: validate
   script:
     - terraform validate

plan:
   stage: plan
   script:
     - terraform plan -out "planfile"
   dependencies:
     - validate
   artifacts:
     paths:
       - planfile

apply:
   stage: apply
   script:
     #- terraform apply -input=false "planfile" -auto-approve
     - terraform apply -auto-approve "planfile" 
   dependencies:
     - plan

destroy:
   stage: destroy
   script:
     #- terraform apply -input=false "planfile" -auto-approve
     - terraform destroy -auto-approve
   dependencies:
     - plan
   when: manual